# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: {}

name: mq-metric-samples

replicaCount: 1
# logLevel: "info"

image:
  repository: replace
  tag: replace
  pullPolicy: IfNotPresent
  port: 9157

# nameOverride: ""
# fullnameOverride: ""

service:
  type: ClusterIP
  port: 9157

route:
  enabled: true

ingress:
  enabled: false
#   appid:
#     enabled: false
#     # web or app - https://cloud.ibm.com/docs/services/appid?topic=appid-kube-auth
#     requestType: web

# #  host: hello
#   namespaceInHost: true
#   subdomain: containers.appdomain.cloud
#   path: "/"

# #  tlsSecretName: ""

# jaeger:
#   enabled: false
#   configName: jaeger-config
#   secretName: jaeger-access
#   collectorEndpoint: http://jaeger-all-in-one-inmemory-collector.openshift-operators.svc.cluster.local:14268/api/traces

vcsInfo:
  repoUrl: ""
  branch: ""

partOf: inventory

connectsTo: QM

configmap:
  CHANNEL: "MONITORING_CHL"
  CONNECTION_NAME: "qm-dev-ibm-mq.dev.svc.cluster.local(1414)"
  QM: "QM1"
  QUEUES: \*,!SYSTEM.*,!AMQ.*
  SUBSCRIPTIONS: \!$SYS*
  TOPICS: \!*
  USE_PUBLICATIONS: "false"
  USE_OBJECT_STATUS: "true"
  CONFIGURATION_FILE: ""
  LOG_LEVEL: "INFO"

# ccdt:
#   enabled: false
#   # IF CCDT_URL has a value, the CHANNEL, CONNECTION_NAME, and QM are configured from CCDT
#   #CCDT_URL: https://ccdt-no-security-dev.free.beeceptor.com/
#   CCDT_URL: file:///ccdt/ccdt.json
#   volumeName: ccdt
#   volumeMountPath: "/ccdt"
#   configMapName: mq-spring-app-ccdt


sealedsecret:
  PASSWORD: AgAlddJNLUgDhZKFdulAddqv8M1KQsXXugkfKuo7CmM+IEBIp8ROA9eDVTcF5hyOKPdo7xQ7sQTbHtUPeYn+iA3/JC74tRByr6BRMQ/uwDewg7zFvTv/mcGOGPFtYFXZq3tNWwKyYKKdZvIkFttNCdPmvLvdIUc/ybgmpMdGJlmi9lZskrv806PtXb4pTuh8BTV4ZP4Sj0TF3EKSbw/GB5C60ICHwqX3ozldUKzQq+bhllJ9JBLCy1kiWwutSjhoRZHraYju1lw5C6OeB6fc0rmbpRUrW67v8Cqcek9Mf37Ke9bjAFRpvItGhvu1ZL/TyAlOKO1tsxcGjxrmwvZ0LLqCAfIaTP0tfrQdv6MAaLakjXhBlVrkraF8YGG8hFjW1upo+BLnrYvmXbb6f1AifS+TWkp75jTg8pghdzNX198w97+rz0ucafaFNQc4nMUEkSzHlYcKf/kKrh/WGmx801en2SYb9+XYa7aHPEwCEVdOo5hc8D7Ll4XovLf3JAC0rueHesAg2+1mk/tqR/E2M8gMw//hsxGKMlYs1I+WIWe8oQ3+Azxo2agac1/uAjWsxVGtforwouzC7J6yQxZO1AP7oGyaLmrcYymIYip5PplhkY1rO/Vb2PXvigv0f085tMsJl415g9MzvTqxpasWOeJ3jpkz5G/n+ygqNsWJQzeVnLf5VF/VQzTbZBSz30/e75A=
  USER: AgAv2nkfY7fbOyVzZ5kHIRMEMHRyQOzFx5Ml2yh3zMghjWHOKWliuECIYPOCT7xCBgxekmfQUb+49DPL4VMw/fRs9wqB4OMbGxE+2RNMS9hNkeQqTL8Ur7Xy85iBFq+FxG+kv2z/hZQe76YcFCOz5w5d4twzJO4Od5G1OAnR1fcKZrg1E1uL13zvMIdBsuuGqtIQdDLMxUV+uUBUaSQlGuuZRkFm2gWNK0vyaKQK2o+2RbCRec8L6bQ+o1uOv21EJk2lDlIogCfyJPdlbVPEkwXyXWIVnsGI9f2he2sZPs4DdtN4tx1YdNMu74p28Gmib9Fdowh9nJjowDdr90GjwKIrzdIOVKGJ1M1bxZyIMpqw27ymQ0F3fhSY5saMlIJwW4+r6wu7TH38MMXjgQXradbqE5xKQgqD/L3uKBU/npAVpwgKkE4SpcvhylpGR2SV5QtUQgX76gGHOvD/xU73YrBL5tnL4nfPDrVokNqREkb8YgtlzaETdS07knkJwBEsVTCFqmzXkuauFz3lhej6sfrKbmzSVkHPDaaKWHKETj7Jfr2cx/pqSsO3j//qtC6ahdY9m3nqzHCIRWlzRAk7hkCDbfiKpHsDChFFQUEGphepejuwdPdXeTKsEcEx/5XYoOJKLZvNS1hYCH2lmLCIRRNlwRGL/pU81kyAXBgFqcGGHD2yryR5CVsV1y67joFpZs4=
  isScopeClusterWide: "true"

# certs:
#   volumeName: certs
#   certSecretName: mq-client-jks
#   certPasswordSecretName: mq-client-jks-password
#   volumeMountPath: "/certs"
#   trustStoreFileName: truststore.jks
#   keyStoreFileName: keystore.jks

# security: false

postSyncJob:
  enabled: false
