kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.name }}
subjects:
  - kind: User
    name: {{ .Values.name }}
roleRef:
  kind: Role
  name: {{ .Values.name }}
  apiGroup: rbac.authorization.k8s.io