apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "{{ .Values.sealedsecret.isScopeClusterWide }}"
  name: {{ .Values.name }}
spec:
  encryptedData:
    IBMMQ_CONNECTION_PASSWORD: {{ .Values.sealedsecret.PASSWORD }}
    IBMMQ_CONNECTION_USER: {{ .Values.sealedsecret.USER }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "{{ .Values.sealedsecret.isScopeClusterWide }}"
      name: {{ .Values.name }}